### ISSUE TITLE
No events on pushEventStream

### ISSUE THREAD

**Issue by timmewe** [emartech/flutter-plugin-for-sap-emarsys-customer-engagement#2]
I followed your documentation to integrate Emarsys into my flutter project. Receiving notifications when the app is not in the foreground is working just fine. Unfortunately I don't receive any events listening to the pushEventStream when the app is running in the foreground. Do you have any ideas what I could have got wrong?

I am testing on an iPhone X running iOS 14.7.1 and Xcode 12.5.1.

**Comment by szabist** [comment]
Hello @timmewe Thanks a lot for working with our plug-in. Not sure if I fully get your set-up but please note that events are not triggered with every incoming push message, they are only supposed to arrive on the pushEventStream if the push message contains an App Event action or a Deep Link action and the user interacts with the push message. The corresponding event handlers in the native SDK are serving this specific purpose of letting the app know if there was a user action on any of the action buttons configured with an App Event or a Deep Link action as detailed here:
https://help.emarsys.com/hc/en-us/articles/360004899457-End-user-guides-Mobile-Engage-Push-messages#tab-actions

If you have such an action added to the push and the event is not received after you interact with the action button then please open a Zendesk ticket instead using your official Emarsys support account and then we can assist you via the Emarsys support.
